watch_dir=/tmp
block_ext=.sh,.exe

watch_dir=/home
block_ext=.sh,.exe

watch_dir=/var/tmp
block_ext=.sh,.exe

watch_dir=/dev/shm

watch_dir=/var/www
allow_ext=.php,.html,.css,.js
block_ext=.sh
trust_ext=.log

watch_dir=/var/log
trust_ext=.log

quarantine_dir=/var/log/sentinel/quarantine
log_file=/var/log/sentinel/sentinel.log
log_max_size=5242880
loop_interval=10
max_actions_per_cycle=50

kill_on_detect=1
